### ISSUE TITLE
Fix Scrawl-Canvas

### ISSUE THREAD

**Issue by gnykka** [slaylines/canvas-engines-comparison#23]
The example with Scrawl-Canvas is broken. It's hidden from the menu but available via direct link: https://benchmarks.slaylines.io/scrawl-canvas.html

Possible problem: Scrawl-Canvas script expects the canvas to be already present on the page.
Also consider refactoring the script — there are a lot of commented lines.

**Comment by KaliedaRik** [comment]
Okay - I'll refactor the code when I get the time.

**Comment by KaliedaRik** [comment]
Hi @gnykka 

The issue is that the scripts for each of the canvas libraries are being loaded in the web page's <head> element. This requirement is set in the layout file `src/pages/layouts/main.pug`.

Current best practice is to load JS files at the end of the page. The Scrawl-canvas library expects the web page's DOM structure to be in place when it runs, so that it can add additional elements to the page - this happens specifically to make sure that any canvas elements already present on the page, or subsequently added to the page by JS code, can be made as accessible as possible via ARIA attributes, etc.

The fix is to move `block scripts` line in the .pug file from the end of the `head` section to the end of the `body` section. I'll prepare a pull request for the fix (alongside refactoring the SC script, as requested in this Issue) by the end of next week.

**Comment by KaliedaRik** [comment]
Hi @gnykka - I've created a pull request for the fix
